### ISSUE TITLE
Does not work with curried functions

### ISSUE THREAD

**Issue by karol-majewski** [chodorowicz/ts-debounce#3]
Thank you for your wonderful library!

#### Steps to reproduce

```ts
const add = (x: number) => (y: number) => x + y;
const delayed = debounce(add, 1000);

delayed(2)(2);
```

#### Expected result

`delayed` returns `4` after at least a second.

#### Actual result

Console throws `Uncaught TypeError: delayed(...) is not a function`.

Maybe it would make sense to restrict function domain to procedures?

```ts
/**
 * A function that emits a side effect and does not return anything.
 */
export type Procedure = (...args: any[]) => void;
```

**Comment by chodorowicz** [comment]
Good point @karol-majewski! Unfortunately it turned out that defining input function as returning void doesn't throw errors when returning functions are provided

```ts
type GetterVoid = () => void;
function getterNumber(): number {
  return 1;
}
const a: GetterVoid = getterNumber; // <-- this doesn't throw an error
```

some explanation here 
https://stackoverflow.com/questions/12761607/typescript-void-return-type-converted-to-any-type

So it seems we cannot type check that.

But I got another idea. Debounce function, instead of returning function which returns nothing, could return promise which would resolve with return value of original function argument. In that way chaining of function and passing arguments between debounced functions could be achieved. I see there are some implementations around the net. Would make sense to add it to this implementation (maybe as an optional thing).

**Comment by karol-majewski** [comment]
```ts
type GetterVoid = () => void;
function getterNumber(): number {
  return 1;
}
const a: GetterVoid = getterNumber; // <-- this doesn't throw an error
```

So disappointing. 😞

**Comment by orta** [comment]
This might be feasible in 4.0 with variadic types

**Comment by chodorowicz** [comment]
As of version `3` the debounced function returns a promise, which is resolved when the original function is called (or rejected when this call is cancelled).

```ts
const add = (x: number) => (y: number) => x + y;
const delayed = debounce(add, 1000);
delayed(2).then(addTwo => {
  addTwo(2) === 4; // true
});
```

I'm closing the issue 🙂
